/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.test.persistence;


import org.backpacker4.bean.jpa.AlbumEntity;
import org.backpacker4.mock.AlbumEntityMock;
import org.backpacker4.persistence.PersistenceServiceProvider;
import org.backpacker4.persistence.services.AlbumPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Album persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class AlbumPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		AlbumPersistence service = PersistenceServiceProvider.getService(AlbumPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Album persistence : delete + load ..." );
		
		AlbumPersistence service = PersistenceServiceProvider.getService(AlbumPersistence.class);
		
		AlbumEntityMock mock = new AlbumEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, (long)0  );
		// process( service, mock, ... );
	}

	private void process(AlbumPersistence service, AlbumEntityMock mock, Long id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		AlbumEntity entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Appuser
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
