/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.test.persistence;


import org.backpacker4.bean.jpa.FeedbackPhotoEntity;
import org.backpacker4.mock.FeedbackPhotoEntityMock;
import org.backpacker4.persistence.PersistenceServiceProvider;
import org.backpacker4.persistence.services.FeedbackPhotoPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for FeedbackPhoto persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class FeedbackPhotoPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		FeedbackPhotoPersistence service = PersistenceServiceProvider.getService(FeedbackPhotoPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test FeedbackPhoto persistence : delete + load ..." );
		
		FeedbackPhotoPersistence service = PersistenceServiceProvider.getService(FeedbackPhotoPersistence.class);
		
		FeedbackPhotoEntityMock mock = new FeedbackPhotoEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, (long)0 , (long)0  );
		// process( service, mock, ... );
	}

	private void process(FeedbackPhotoPersistence service, FeedbackPhotoEntityMock mock, Long idFeedback, Long idPhoto ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		FeedbackPhotoEntity entity = service.load( idFeedback, idPhoto );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( idFeedback, idPhoto ) ;
			Assert.assertNotNull(entity);

			/* NB : this entity is a "Join Table" 
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( idFeedback, idPhoto );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
