/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.test.persistence;


import org.backpacker4.bean.jpa.PositionEntity;
import org.backpacker4.mock.PositionEntityMock;
import org.backpacker4.persistence.PersistenceServiceProvider;
import org.backpacker4.persistence.services.PositionPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Position persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class PositionPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		PositionPersistence service = PersistenceServiceProvider.getService(PositionPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Position persistence : delete + load ..." );
		
		PositionPersistence service = PersistenceServiceProvider.getService(PositionPersistence.class);
		
		PositionEntityMock mock = new PositionEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, (long)0  );
		// process( service, mock, ... );
	}

	private void process(PositionPersistence service, PositionEntityMock mock, Long id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		PositionEntity entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
