/*
 * Created on 28 okt 2015 ( Time 11:01:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.test.persistence;


import org.backpacker4.bean.jpa.UserRolesEntity;
import org.backpacker4.mock.UserRolesEntityMock;
import org.backpacker4.persistence.PersistenceServiceProvider;
import org.backpacker4.persistence.services.UserRolesPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for UserRoles persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class UserRolesPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		UserRolesPersistence service = PersistenceServiceProvider.getService(UserRolesPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test UserRoles persistence : delete + load ..." );
		
		UserRolesPersistence service = PersistenceServiceProvider.getService(UserRolesPersistence.class);
		
		UserRolesEntityMock mock = new UserRolesEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(UserRolesPersistence service, UserRolesEntityMock mock, Integer iduserRoles ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		UserRolesEntity entity = service.load( iduserRoles );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( iduserRoles ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Appuser
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( iduserRoles );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
