/*
 * Created on 28 okt 2015 ( Time 11:00:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.bean;

import java.io.Serializable;

import javax.validation.constraints.*;


public class UserRoles_original implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer iduserRoles;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    @Size( min = 1, max = 45 )
    private String username;

    @NotNull
    @Size( min = 1, max = 45 )
    private String userrole;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setIduserRoles( Integer iduserRoles ) {
        this.iduserRoles = iduserRoles ;
    }

    public Integer getIduserRoles() {
        return this.iduserRoles;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUsername( String username ) {
        this.username = username;
    }
    public String getUsername() {
        return this.username;
    }

    public void setUserrole( String userrole ) {
        this.userrole = userrole;
    }
    public String getUserrole() {
        return this.userrole;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(iduserRoles);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(userrole);
        return sb.toString(); 
    } 


}
