///*
// * Created on 28 okt 2015 ( Time 11:01:17 )
// * Generated by Telosys Tools Generator ( version 2.1.1 )
// */
//package org.backpacker4.business.service.mapping;
//
//import org.modelmapper.ModelMapper;
//import org.modelmapper.convention.MatchingStrategies;
//import org.springframework.stereotype.Component;
//import org.backpacker4.bean.UserRoles;
//import org.backpacker4.bean.jpa.UserRolesEntity;
//import org.backpacker4.bean.jpa.AppuserEntity;
//
///**
// * Mapping between entity beans and display beans.
// */
//@Component
//public class UserRolesServiceMapper_original extends AbstractServiceMapper {
//
//	/**
//	 * ModelMapper : bean to bean mapping library.
//	 */
//	private ModelMapper modelMapper;
//	
//	/**
//	 * Constructor.
//	 */
//	public UserRolesServiceMapper_original() {
//		modelMapper = new ModelMapper();
//		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
//	}
//
//	/**
//	 * Mapping from 'UserRolesEntity' to 'UserRoles'
//	 * @param userRolesEntity
//	 */
//	public UserRoles mapUserRolesEntityToUserRoles(UserRolesEntity userRolesEntity) {
//		if(userRolesEntity == null) {
//			System.out.println("Hier gaat het fout: userRolesEntity set to null ");
//			return null;
//		}
//
//		//--- Generic mapping 
//		UserRoles userRoles = map(userRolesEntity, UserRoles.class);
//
//		//--- Link mapping ( link to Appuser )
//		if(userRolesEntity.getAppuser() != null) {
//			userRoles.setUsername(userRolesEntity.getAppuser().getUsername());
//		}
//		else {
//			System.out.println("Hier gaat het fout: userRolesEntity.getAppuser set to null ");
//		}
//		return userRoles;
//	}
//	
//	/**
//	 * Mapping from 'UserRoles' to 'UserRolesEntity'
//	 * @param userRoles
//	 * @param userRolesEntity
//	 */
//	public void mapUserRolesToUserRolesEntity(UserRoles userRoles, UserRolesEntity userRolesEntity) {
//		if(userRoles == null) {
//			return;
//		}
//
//		//--- Generic mapping 
//		map(userRoles, userRolesEntity);
//
//		//--- Link mapping ( link : userRoles )
//		if( hasLinkToAppuser(userRoles) ) {
//			AppuserEntity appuser1 = new AppuserEntity();
//			appuser1.setUsername( userRoles.getUsername() );
//			userRolesEntity.setAppuser( appuser1 );
//			System.out.println("userrolesEntity has username " + userRolesEntity.getAppuser().getUsername());
//		} else {
//			userRolesEntity.setAppuser( null );
//			System.out.println("Hier gaat het fout: appusers set to null ");
//		}
//
//	}
//	
//	/**
//	 * Verify that Appuser id is valid.
//	 * @param Appuser Appuser
//	 * @return boolean
//	 */
//	private boolean hasLinkToAppuser(UserRoles userRoles) {
//		if(userRoles.getUsername() != null) {
//			System.out.println("userroles has username " + userRoles.getUsername());
//			return true;
//		}
//		System.out.println("no username found in userroles");
//		return false;
//	}
//
//	/**
//	 * {@inheritDoc}
//	 */
//	@Override
//	protected ModelMapper getModelMapper() {
//		return modelMapper;
//	}
//
//	protected void setModelMapper(ModelMapper modelMapper) {
//		this.modelMapper = modelMapper;
//	}
//
//}