/*
 * Created on 28 okt 2015 ( Time 11:00:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.backpacker4.web.common.AbstractController;
import org.backpacker4.web.common.FormMode;
import org.backpacker4.web.common.Message;
import org.backpacker4.web.common.MessageType;

//--- Entities
import org.backpacker4.bean.AlbumPhoto;

//--- Services 
import org.backpacker4.business.service.AlbumPhotoService;


/**
 * Spring MVC controller for 'AlbumPhoto' management.
 */
@Controller
@RequestMapping("/albumPhoto")
public class AlbumPhotoController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "albumPhoto";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "albumPhoto/form";
	private static final String JSP_LIST   = "albumPhoto/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/albumPhoto/create";
	private static final String SAVE_ACTION_UPDATE   = "/albumPhoto/update";

	//--- Main entity service
	@Resource
    private AlbumPhotoService albumPhotoService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public AlbumPhotoController() {
		super(AlbumPhotoController.class, MAIN_ENTITY_NAME );
		log("AlbumPhotoController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param albumPhoto
	 */
	private void populateModel(Model model, AlbumPhoto albumPhoto, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, albumPhoto);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of AlbumPhoto found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<AlbumPhoto> list = albumPhotoService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new AlbumPhoto
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		AlbumPhoto albumPhoto = new AlbumPhoto();	
		populateModel( model, albumPhoto, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing AlbumPhoto
	 * @param model Spring MVC model
	 * @param idAlbum  primary key element
	 * @param idPhoto  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{idAlbum}/{idPhoto}")
	public String formForUpdate(Model model, @PathVariable("idAlbum") Long idAlbum, @PathVariable("idPhoto") Long idPhoto ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		AlbumPhoto albumPhoto = albumPhotoService.findById(idAlbum, idPhoto);
		populateModel( model, albumPhoto, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param albumPhoto  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid AlbumPhoto albumPhoto, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				AlbumPhoto albumPhotoCreated = albumPhotoService.create(albumPhoto); 
				model.addAttribute(MAIN_ENTITY_NAME, albumPhotoCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, albumPhoto.getIdAlbum(), albumPhoto.getIdPhoto() );
			} else {
				populateModel( model, albumPhoto, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "albumPhoto.error.create", e);
			populateModel( model, albumPhoto, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param albumPhoto  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid AlbumPhoto albumPhoto, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				AlbumPhoto albumPhotoSaved = albumPhotoService.update(albumPhoto);
				model.addAttribute(MAIN_ENTITY_NAME, albumPhotoSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, albumPhoto.getIdAlbum(), albumPhoto.getIdPhoto());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, albumPhoto, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "albumPhoto.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, albumPhoto, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param idAlbum  primary key element
	 * @param idPhoto  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{idAlbum}/{idPhoto}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("idAlbum") Long idAlbum, @PathVariable("idPhoto") Long idPhoto) {
		log("Action 'delete'" );
		try {
			albumPhotoService.delete( idAlbum, idPhoto );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "albumPhoto.error.delete", e);
		}
		return redirectToList();
	}

}
