/*
 * Created on 28 okt 2015 ( Time 11:00:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.web.controller;

import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.backpacker4.web.common.AbstractController;
import org.backpacker4.web.common.FormMode;
import org.backpacker4.web.common.Message;
import org.backpacker4.web.common.MessageType;

//--- Entities
import org.backpacker4.bean.FeedbackPhoto;

//--- Services 
import org.backpacker4.business.service.FeedbackPhotoService;


/**
 * Spring MVC controller for 'FeedbackPhoto' management.
 */
@Controller
@RequestMapping("/feedbackPhoto")
public class FeedbackPhotoController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "feedbackPhoto";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "feedbackPhoto/form";
	private static final String JSP_LIST   = "feedbackPhoto/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/feedbackPhoto/create";
	private static final String SAVE_ACTION_UPDATE   = "/feedbackPhoto/update";

	//--- Main entity service
	@Resource
    private FeedbackPhotoService feedbackPhotoService; // Injected by Spring
	//--- Other service(s)

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public FeedbackPhotoController() {
		super(FeedbackPhotoController.class, MAIN_ENTITY_NAME );
		log("FeedbackPhotoController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param feedbackPhoto
	 */
	private void populateModel(Model model, FeedbackPhoto feedbackPhoto, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, feedbackPhoto);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of FeedbackPhoto found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<FeedbackPhoto> list = feedbackPhotoService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new FeedbackPhoto
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		FeedbackPhoto feedbackPhoto = new FeedbackPhoto();	
		populateModel( model, feedbackPhoto, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing FeedbackPhoto
	 * @param model Spring MVC model
	 * @param idFeedback  primary key element
	 * @param idPhoto  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{idFeedback}/{idPhoto}")
	public String formForUpdate(Model model, @PathVariable("idFeedback") Long idFeedback, @PathVariable("idPhoto") Long idPhoto ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		FeedbackPhoto feedbackPhoto = feedbackPhotoService.findById(idFeedback, idPhoto);
		populateModel( model, feedbackPhoto, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param feedbackPhoto  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid FeedbackPhoto feedbackPhoto, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				FeedbackPhoto feedbackPhotoCreated = feedbackPhotoService.create(feedbackPhoto); 
				model.addAttribute(MAIN_ENTITY_NAME, feedbackPhotoCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, feedbackPhoto.getIdFeedback(), feedbackPhoto.getIdPhoto() );
			} else {
				populateModel( model, feedbackPhoto, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "feedbackPhoto.error.create", e);
			populateModel( model, feedbackPhoto, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param feedbackPhoto  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid FeedbackPhoto feedbackPhoto, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				FeedbackPhoto feedbackPhotoSaved = feedbackPhotoService.update(feedbackPhoto);
				model.addAttribute(MAIN_ENTITY_NAME, feedbackPhotoSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, feedbackPhoto.getIdFeedback(), feedbackPhoto.getIdPhoto());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, feedbackPhoto, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "feedbackPhoto.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, feedbackPhoto, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param idFeedback  primary key element
	 * @param idPhoto  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{idFeedback}/{idPhoto}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("idFeedback") Long idFeedback, @PathVariable("idPhoto") Long idPhoto) {
		log("Action 'delete'" );
		try {
			feedbackPhotoService.delete( idFeedback, idPhoto );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "feedbackPhoto.error.delete", e);
		}
		return redirectToList();
	}

}
