/*
 * Created on 28 okt 2015 ( Time 11:00:54 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import org.backpacker4.web.common.AbstractController;
import org.backpacker4.web.common.FormMode;
import org.backpacker4.web.common.Message;
import org.backpacker4.web.common.MessageType;

//--- Entities
import org.backpacker4.bean.Feedback;
import org.backpacker4.bean.Appuser;
import org.backpacker4.bean.Photo;
import org.backpacker4.bean.Typeinfo;
import org.backpacker4.bean.Position;

//--- Services 
import org.backpacker4.business.service.FeedbackService;
import org.backpacker4.business.service.AppuserService;
import org.backpacker4.business.service.PhotoService;
import org.backpacker4.business.service.TypeinfoService;
import org.backpacker4.business.service.PositionService;

//--- List Items 
import org.backpacker4.web.listitem.AppuserListItem;
import org.backpacker4.web.listitem.PhotoListItem;
import org.backpacker4.web.listitem.TypeinfoListItem;
import org.backpacker4.web.listitem.PositionListItem;

/**
 * Spring MVC controller for 'Feedback' management.
 */
@Controller
@RequestMapping("/feedback")
public class FeedbackController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "feedback";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "feedback/form";
	private static final String JSP_LIST   = "feedback/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/feedback/create";
	private static final String SAVE_ACTION_UPDATE   = "/feedback/update";

	//--- Main entity service
	@Resource
    private FeedbackService feedbackService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private AppuserService appuserService; // Injected by Spring
	@Resource
    private PhotoService photoService; // Injected by Spring
	@Resource
    private TypeinfoService typeinfoService; // Injected by Spring
	@Resource
    private PositionService positionService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public FeedbackController() {
		super(FeedbackController.class, MAIN_ENTITY_NAME );
		log("FeedbackController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Appuser"
	 * @param model
	 */
	private void populateListOfAppuserItems(Model model) {
		List<Appuser> list = appuserService.findAll();
		List<AppuserListItem> items = new LinkedList<AppuserListItem>();
		for ( Appuser appuser : list ) {
			items.add(new AppuserListItem( appuser ) );
		}
		model.addAttribute("listOfAppuserItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Photo"
	 * @param model
	 */
	private void populateListOfPhotoItems(Model model) {
		List<Photo> list = photoService.findAll();
		List<PhotoListItem> items = new LinkedList<PhotoListItem>();
		for ( Photo photo : list ) {
			items.add(new PhotoListItem( photo ) );
		}
		model.addAttribute("listOfPhotoItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Typeinfo"
	 * @param model
	 */
	private void populateListOfTypeinfoItems(Model model) {
		List<Typeinfo> list = typeinfoService.findAll();
		List<TypeinfoListItem> items = new LinkedList<TypeinfoListItem>();
		for ( Typeinfo typeinfo : list ) {
			items.add(new TypeinfoListItem( typeinfo ) );
		}
		model.addAttribute("listOfTypeinfoItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Position"
	 * @param model
	 */
	private void populateListOfPositionItems(Model model) {
		List<Position> list = positionService.findAll();
		List<PositionListItem> items = new LinkedList<PositionListItem>();
		for ( Position position : list ) {
			items.add(new PositionListItem( position ) );
		}
		model.addAttribute("listOfPositionItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param feedback
	 */
	private void populateModel(Model model, Feedback feedback, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, feedback);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfAppuserItems(model);
			populateListOfPhotoItems(model);
			populateListOfTypeinfoItems(model);
			populateListOfPositionItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfAppuserItems(model);
			populateListOfTypeinfoItems(model);
			populateListOfPositionItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Feedback found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Feedback> list = feedbackService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Feedback
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Feedback feedback = new Feedback();	
		populateModel( model, feedback, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Feedback
	 * @param model Spring MVC model
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{id}")
	public String formForUpdate(Model model, @PathVariable("id") Long id ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Feedback feedback = feedbackService.findById(id);
		populateModel( model, feedback, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param feedback  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Feedback feedback, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Feedback feedbackCreated = feedbackService.create(feedback); 
				model.addAttribute(MAIN_ENTITY_NAME, feedbackCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, feedback.getId() );
			} else {
				populateModel( model, feedback, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "feedback.error.create", e);
			populateModel( model, feedback, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param feedback  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Feedback feedback, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Feedback feedbackSaved = feedbackService.update(feedback);
				model.addAttribute(MAIN_ENTITY_NAME, feedbackSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, feedback.getId());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, feedback, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "feedback.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, feedback, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param id  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{id}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("id") Long id) {
		log("Action 'delete'" );
		try {
			feedbackService.delete( id );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "feedback.error.delete", e);
		}
		return redirectToList();
	}

}
