/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.backpacker4.bean.jpa.AlbumPhotoEntity;
import org.backpacker4.persistence.commons.fake.GenericFakeService;
import org.backpacker4.persistence.services.AlbumPhotoPersistence;

/**
 * Fake persistence service implementation ( entity "AlbumPhoto" )
 *
 * @author Telosys Tools Generator
 */
public class AlbumPhotoPersistenceFAKE extends GenericFakeService<AlbumPhotoEntity> implements AlbumPhotoPersistence {

	public AlbumPhotoPersistenceFAKE () {
		super(AlbumPhotoEntity.class);
	}
	
	protected AlbumPhotoEntity buildEntity(int index) {
		AlbumPhotoEntity entity = new AlbumPhotoEntity();
		// Init fields with mock values
		entity.setIdAlbum( nextLong() ) ;
		entity.setIdPhoto( nextLong() ) ;
		return entity ;
	}
	
	
	public boolean delete(AlbumPhotoEntity entity) {
		log("delete ( AlbumPhotoEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long idAlbum, Long idPhoto ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(AlbumPhotoEntity entity) {
		log("insert ( AlbumPhotoEntity : " + entity + ")" ) ;
	}

	public AlbumPhotoEntity load( Long idAlbum, Long idPhoto ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<AlbumPhotoEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<AlbumPhotoEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<AlbumPhotoEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public AlbumPhotoEntity save(AlbumPhotoEntity entity) {
		log("insert ( AlbumPhotoEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<AlbumPhotoEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
