/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.backpacker4.bean.jpa.AlbumEntity;
import org.backpacker4.persistence.commons.fake.GenericFakeService;
import org.backpacker4.persistence.services.AlbumPersistence;

/**
 * Fake persistence service implementation ( entity "Album" )
 *
 * @author Telosys Tools Generator
 */
public class AlbumPersistenceFAKE extends GenericFakeService<AlbumEntity> implements AlbumPersistence {

	public AlbumPersistenceFAKE () {
		super(AlbumEntity.class);
	}
	
	protected AlbumEntity buildEntity(int index) {
		AlbumEntity entity = new AlbumEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setAlbumname( nextString() ) ;
		entity.setComment( nextString() ) ;
		entity.setDatealbum( nextDate() ) ;
		return entity ;
	}
	
	
	public boolean delete(AlbumEntity entity) {
		log("delete ( AlbumEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(AlbumEntity entity) {
		log("insert ( AlbumEntity : " + entity + ")" ) ;
	}

	public AlbumEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<AlbumEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<AlbumEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<AlbumEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public AlbumEntity save(AlbumEntity entity) {
		log("insert ( AlbumEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<AlbumEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
