/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.backpacker4.bean.jpa.AppuserEntity;
import org.backpacker4.persistence.commons.fake.GenericFakeService;
import org.backpacker4.persistence.services.AppuserPersistence;

/**
 * Fake persistence service implementation ( entity "Appuser" )
 *
 * @author Telosys Tools Generator
 */
public class AppuserPersistenceFAKE extends GenericFakeService<AppuserEntity> implements AppuserPersistence {

	public AppuserPersistenceFAKE () {
		super(AppuserEntity.class);
	}
	
	protected AppuserEntity buildEntity(int index) {
		AppuserEntity entity = new AppuserEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setFirstname( nextString() ) ;
		entity.setLastname( nextString() ) ;
		entity.setEmail( nextString() ) ;
		entity.setUsername( nextString() ) ;
		entity.setUserpassword( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(AppuserEntity entity) {
		log("delete ( AppuserEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(AppuserEntity entity) {
		log("insert ( AppuserEntity : " + entity + ")" ) ;
	}

	public AppuserEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<AppuserEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<AppuserEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<AppuserEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public AppuserEntity save(AppuserEntity entity) {
		log("insert ( AppuserEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<AppuserEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
