/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.backpacker4.bean.jpa.FeedbackEntity;
import org.backpacker4.persistence.commons.fake.GenericFakeService;
import org.backpacker4.persistence.services.FeedbackPersistence;

/**
 * Fake persistence service implementation ( entity "Feedback" )
 *
 * @author Telosys Tools Generator
 */
public class FeedbackPersistenceFAKE extends GenericFakeService<FeedbackEntity> implements FeedbackPersistence {

	public FeedbackPersistenceFAKE () {
		super(FeedbackEntity.class);
	}
	
	protected FeedbackEntity buildEntity(int index) {
		FeedbackEntity entity = new FeedbackEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setComment( nextString() ) ;
		entity.setDatefeedback( nextDate() ) ;
		return entity ;
	}
	
	
	public boolean delete(FeedbackEntity entity) {
		log("delete ( FeedbackEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(FeedbackEntity entity) {
		log("insert ( FeedbackEntity : " + entity + ")" ) ;
	}

	public FeedbackEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<FeedbackEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<FeedbackEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<FeedbackEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public FeedbackEntity save(FeedbackEntity entity) {
		log("insert ( FeedbackEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<FeedbackEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
