/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.backpacker4.bean.jpa.FeedbackPhotoEntity;
import org.backpacker4.persistence.commons.fake.GenericFakeService;
import org.backpacker4.persistence.services.FeedbackPhotoPersistence;

/**
 * Fake persistence service implementation ( entity "FeedbackPhoto" )
 *
 * @author Telosys Tools Generator
 */
public class FeedbackPhotoPersistenceFAKE extends GenericFakeService<FeedbackPhotoEntity> implements FeedbackPhotoPersistence {

	public FeedbackPhotoPersistenceFAKE () {
		super(FeedbackPhotoEntity.class);
	}
	
	protected FeedbackPhotoEntity buildEntity(int index) {
		FeedbackPhotoEntity entity = new FeedbackPhotoEntity();
		// Init fields with mock values
		entity.setIdFeedback( nextLong() ) ;
		entity.setIdPhoto( nextLong() ) ;
		return entity ;
	}
	
	
	public boolean delete(FeedbackPhotoEntity entity) {
		log("delete ( FeedbackPhotoEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long idFeedback, Long idPhoto ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(FeedbackPhotoEntity entity) {
		log("insert ( FeedbackPhotoEntity : " + entity + ")" ) ;
	}

	public FeedbackPhotoEntity load( Long idFeedback, Long idPhoto ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<FeedbackPhotoEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<FeedbackPhotoEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<FeedbackPhotoEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public FeedbackPhotoEntity save(FeedbackPhotoEntity entity) {
		log("insert ( FeedbackPhotoEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<FeedbackPhotoEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
