/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.backpacker4.bean.jpa.PhotoEntity;
import org.backpacker4.persistence.commons.fake.GenericFakeService;
import org.backpacker4.persistence.services.PhotoPersistence;

/**
 * Fake persistence service implementation ( entity "Photo" )
 *
 * @author Telosys Tools Generator
 */
public class PhotoPersistenceFAKE extends GenericFakeService<PhotoEntity> implements PhotoPersistence {

	public PhotoPersistenceFAKE () {
		super(PhotoEntity.class);
	}
	
	protected PhotoEntity buildEntity(int index) {
		PhotoEntity entity = new PhotoEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setDescription( nextString() ) ;
		entity.setDatetaken( nextDate() ) ;
		entity.setComment( nextString() ) ;
		entity.setFullphoto( nextString() ) ;
		entity.setThumbnail( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(PhotoEntity entity) {
		log("delete ( PhotoEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(PhotoEntity entity) {
		log("insert ( PhotoEntity : " + entity + ")" ) ;
	}

	public PhotoEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<PhotoEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<PhotoEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<PhotoEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public PhotoEntity save(PhotoEntity entity) {
		log("insert ( PhotoEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<PhotoEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
