/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.backpacker4.bean.jpa.PositionEntity;
import org.backpacker4.persistence.commons.fake.GenericFakeService;
import org.backpacker4.persistence.services.PositionPersistence;

/**
 * Fake persistence service implementation ( entity "Position" )
 *
 * @author Telosys Tools Generator
 */
public class PositionPersistenceFAKE extends GenericFakeService<PositionEntity> implements PositionPersistence {

	public PositionPersistenceFAKE () {
		super(PositionEntity.class);
	}
	
	protected PositionEntity buildEntity(int index) {
		PositionEntity entity = new PositionEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		return entity ;
	}
	
	
	public boolean delete(PositionEntity entity) {
		log("delete ( PositionEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(PositionEntity entity) {
		log("insert ( PositionEntity : " + entity + ")" ) ;
	}

	public PositionEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<PositionEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<PositionEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<PositionEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public PositionEntity save(PositionEntity entity) {
		log("insert ( PositionEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<PositionEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
