/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.backpacker4.bean.jpa.TypeinfoEntity;
import org.backpacker4.persistence.commons.fake.GenericFakeService;
import org.backpacker4.persistence.services.TypeinfoPersistence;

/**
 * Fake persistence service implementation ( entity "Typeinfo" )
 *
 * @author Telosys Tools Generator
 */
public class TypeinfoPersistenceFAKE extends GenericFakeService<TypeinfoEntity> implements TypeinfoPersistence {

	public TypeinfoPersistenceFAKE () {
		super(TypeinfoEntity.class);
	}
	
	protected TypeinfoEntity buildEntity(int index) {
		TypeinfoEntity entity = new TypeinfoEntity();
		// Init fields with mock values
		entity.setId( nextLong() ) ;
		entity.setDescription( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(TypeinfoEntity entity) {
		log("delete ( TypeinfoEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Long id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(TypeinfoEntity entity) {
		log("insert ( TypeinfoEntity : " + entity + ")" ) ;
	}

	public TypeinfoEntity load( Long id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<TypeinfoEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<TypeinfoEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<TypeinfoEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public TypeinfoEntity save(TypeinfoEntity entity) {
		log("insert ( TypeinfoEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<TypeinfoEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
