/*
 * Created on 28 okt 2015 ( Time 11:01:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.backpacker4.bean.AlbumPhoto;
import org.backpacker4.bean.jpa.AlbumPhotoEntity;
import org.backpacker4.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class AlbumPhotoServiceMapperTest {

	private AlbumPhotoServiceMapper albumPhotoServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		albumPhotoServiceMapper = new AlbumPhotoServiceMapper();
		albumPhotoServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'AlbumPhotoEntity' to 'AlbumPhoto'
	 * @param albumPhotoEntity
	 */
	@Test
	public void testMapAlbumPhotoEntityToAlbumPhoto() {
		// Given
		AlbumPhotoEntity albumPhotoEntity = new AlbumPhotoEntity();
		
		// When
		AlbumPhoto albumPhoto = albumPhotoServiceMapper.mapAlbumPhotoEntityToAlbumPhoto(albumPhotoEntity);
		
		// Then
	}
	
	/**
	 * Test : Mapping from 'AlbumPhoto' to 'AlbumPhotoEntity'
	 */
	@Test
	public void testMapAlbumPhotoToAlbumPhotoEntity() {
		// Given
		AlbumPhoto albumPhoto = new AlbumPhoto();

		AlbumPhotoEntity albumPhotoEntity = new AlbumPhotoEntity();
		
		// When
		albumPhotoServiceMapper.mapAlbumPhotoToAlbumPhotoEntity(albumPhoto, albumPhotoEntity);
		
		// Then
	}

}