/*
 * Created on 28 okt 2015 ( Time 11:01:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.backpacker4.bean.FeedbackPhoto;
import org.backpacker4.bean.jpa.FeedbackPhotoEntity;
import org.backpacker4.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class FeedbackPhotoServiceMapperTest {

	private FeedbackPhotoServiceMapper feedbackPhotoServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		feedbackPhotoServiceMapper = new FeedbackPhotoServiceMapper();
		feedbackPhotoServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'FeedbackPhotoEntity' to 'FeedbackPhoto'
	 * @param feedbackPhotoEntity
	 */
	@Test
	public void testMapFeedbackPhotoEntityToFeedbackPhoto() {
		// Given
		FeedbackPhotoEntity feedbackPhotoEntity = new FeedbackPhotoEntity();
		
		// When
		FeedbackPhoto feedbackPhoto = feedbackPhotoServiceMapper.mapFeedbackPhotoEntityToFeedbackPhoto(feedbackPhotoEntity);
		
		// Then
	}
	
	/**
	 * Test : Mapping from 'FeedbackPhoto' to 'FeedbackPhotoEntity'
	 */
	@Test
	public void testMapFeedbackPhotoToFeedbackPhotoEntity() {
		// Given
		FeedbackPhoto feedbackPhoto = new FeedbackPhoto();

		FeedbackPhotoEntity feedbackPhotoEntity = new FeedbackPhotoEntity();
		
		// When
		feedbackPhotoServiceMapper.mapFeedbackPhotoToFeedbackPhotoEntity(feedbackPhoto, feedbackPhotoEntity);
		
		// Then
	}

}