/*
 * Created on 28 okt 2015 ( Time 11:01:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.backpacker4.bean.Position;
import org.backpacker4.bean.jpa.PositionEntity;
import org.backpacker4.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class PositionServiceMapperTest {

	private PositionServiceMapper positionServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		positionServiceMapper = new PositionServiceMapper();
		positionServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'PositionEntity' to 'Position'
	 * @param positionEntity
	 */
	@Test
	public void testMapPositionEntityToPosition() {
		// Given
		PositionEntity positionEntity = new PositionEntity();
		positionEntity.setLatitude(mockValues.nextBigDecimal());
		positionEntity.setLongitude(mockValues.nextBigDecimal());
		
		// When
		Position position = positionServiceMapper.mapPositionEntityToPosition(positionEntity);
		
		// Then
		assertEquals(positionEntity.getLatitude(), position.getLatitude());
		assertEquals(positionEntity.getLongitude(), position.getLongitude());
	}
	
	/**
	 * Test : Mapping from 'Position' to 'PositionEntity'
	 */
	@Test
	public void testMapPositionToPositionEntity() {
		// Given
		Position position = new Position();
		position.setLatitude(mockValues.nextBigDecimal());
		position.setLongitude(mockValues.nextBigDecimal());

		PositionEntity positionEntity = new PositionEntity();
		
		// When
		positionServiceMapper.mapPositionToPositionEntity(position, positionEntity);
		
		// Then
		assertEquals(position.getLatitude(), positionEntity.getLatitude());
		assertEquals(position.getLongitude(), positionEntity.getLongitude());
	}

}