/*
 * Created on 28 okt 2015 ( Time 11:01:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.backpacker4.bean.Typeinfo;
import org.backpacker4.bean.jpa.TypeinfoEntity;
import org.backpacker4.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class TypeinfoServiceMapperTest {

	private TypeinfoServiceMapper typeinfoServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		typeinfoServiceMapper = new TypeinfoServiceMapper();
		typeinfoServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'TypeinfoEntity' to 'Typeinfo'
	 * @param typeinfoEntity
	 */
	@Test
	public void testMapTypeinfoEntityToTypeinfo() {
		// Given
		TypeinfoEntity typeinfoEntity = new TypeinfoEntity();
		typeinfoEntity.setDescription(mockValues.nextString(100));
		
		// When
		Typeinfo typeinfo = typeinfoServiceMapper.mapTypeinfoEntityToTypeinfo(typeinfoEntity);
		
		// Then
		assertEquals(typeinfoEntity.getDescription(), typeinfo.getDescription());
	}
	
	/**
	 * Test : Mapping from 'Typeinfo' to 'TypeinfoEntity'
	 */
	@Test
	public void testMapTypeinfoToTypeinfoEntity() {
		// Given
		Typeinfo typeinfo = new Typeinfo();
		typeinfo.setDescription(mockValues.nextString(100));

		TypeinfoEntity typeinfoEntity = new TypeinfoEntity();
		
		// When
		typeinfoServiceMapper.mapTypeinfoToTypeinfoEntity(typeinfo, typeinfoEntity);
		
		// Then
		assertEquals(typeinfo.getDescription(), typeinfoEntity.getDescription());
	}

}