/*
 * Created on 28 okt 2015 ( Time 11:01:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.business.service.mapping;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.backpacker4.bean.UserRoles;
import org.backpacker4.bean.jpa.UserRolesEntity;
import org.backpacker4.bean.jpa.AppuserEntity;
import org.backpacker4.test.MockValues;

/**
 * Test : Mapping between entity beans and display beans.
 */
public class UserRolesServiceMapperTest {

	private UserRolesServiceMapper userRolesServiceMapper;

	private static ModelMapper modelMapper = new ModelMapper();

	private MockValues mockValues = new MockValues();
	
	
	@BeforeClass
	public static void setUp() {
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}
	
	@Before
	public void before() {
		userRolesServiceMapper = new UserRolesServiceMapper();
		userRolesServiceMapper.setModelMapper(modelMapper);
	}
	
	/**
	 * Mapping from 'UserRolesEntity' to 'UserRoles'
	 * @param userRolesEntity
	 */
	@Test
	public void testMapUserRolesEntityToUserRoles() {
		// Given
		UserRolesEntity userRolesEntity = new UserRolesEntity();
		userRolesEntity.setUserrole(mockValues.nextString(45));
		userRolesEntity.setAppuser(new AppuserEntity());
		userRolesEntity.getAppuser().setUsername(mockValues.nextString(50));
		
		// When
		UserRoles userRoles = userRolesServiceMapper.mapUserRolesEntityToUserRoles(userRolesEntity);
		
		// Then
		assertEquals(userRolesEntity.getUserrole(), userRoles.getUserrole());
		assertEquals(userRolesEntity.getAppuser().getUsername(), userRoles.getUsername());
	}
	
	/**
	 * Test : Mapping from 'UserRoles' to 'UserRolesEntity'
	 */
	@Test
	public void testMapUserRolesToUserRolesEntity() {
		// Given
		UserRoles userRoles = new UserRoles();
		userRoles.setUserrole(mockValues.nextString(45));
		userRoles.setUsername(mockValues.nextString(45));

		UserRolesEntity userRolesEntity = new UserRolesEntity();
		
		// When
		userRolesServiceMapper.mapUserRolesToUserRolesEntity(userRoles, userRolesEntity);
		
		// Then
		assertEquals(userRoles.getUserrole(), userRolesEntity.getUserrole());
		assertEquals(userRoles.getUsername(), userRolesEntity.getAppuser().getUsername());
	}

}