
/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.mock;

import java.util.LinkedList;
import java.util.List;

import org.backpacker4.bean.jpa.AlbumPhotoEntity;
import org.backpacker4.mock.tool.MockValues;

public class AlbumPhotoEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public AlbumPhotoEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextLong(), mockValues.nextLong() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public AlbumPhotoEntity createInstance( Long idAlbum, Long idPhoto ) {
		AlbumPhotoEntity entity = new AlbumPhotoEntity();
		// Init Primary Key fields
		entity.setIdAlbum( idAlbum) ;
		entity.setIdPhoto( idPhoto) ;
		// Init Data fields
		// Init Link fields (if any)
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<AlbumPhotoEntity> createList(int count) {
		List<AlbumPhotoEntity> list = new LinkedList<AlbumPhotoEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
