
/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.mock;

import java.util.LinkedList;
import java.util.List;

import org.backpacker4.bean.jpa.AppuserEntity;
import org.backpacker4.mock.tool.MockValues;

public class AppuserEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public AppuserEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextLong() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public AppuserEntity createInstance( Long id ) {
		AppuserEntity entity = new AppuserEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setFirstname( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setLastname( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setEmail( mockValues.nextString(150) ) ; // java.lang.String 
		entity.setUsername( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setUserpassword( mockValues.nextString(50) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setPosition( TODO ) ; // Position 
		// setListOfUserRoles( TODO ) ; // List<UserRoles> 
		// setPhoto( TODO ) ; // Photo 
		// setListOfAlbum( TODO ) ; // List<Album> 
		// setListOfFeedback( TODO ) ; // List<Feedback> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<AppuserEntity> createList(int count) {
		List<AppuserEntity> list = new LinkedList<AppuserEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
