
/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.mock;

import java.util.LinkedList;
import java.util.List;

import org.backpacker4.bean.jpa.FeedbackEntity;
import org.backpacker4.mock.tool.MockValues;

public class FeedbackEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public FeedbackEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextLong() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public FeedbackEntity createInstance( Long id ) {
		FeedbackEntity entity = new FeedbackEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setComment( mockValues.nextString(2147483647) ) ; // java.lang.String 
		entity.setDatefeedback( mockValues.nextDate() ) ; // java.util.Date 
		// Init Link fields (if any)
		// setAppuser( TODO ) ; // Appuser 
		// setListOfPhoto( TODO ) ; // List<Photo> 
		// setTypeinfo( TODO ) ; // Typeinfo 
		// setPosition( TODO ) ; // Position 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<FeedbackEntity> createList(int count) {
		List<FeedbackEntity> list = new LinkedList<FeedbackEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
