
/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.mock;

import java.util.LinkedList;
import java.util.List;

import org.backpacker4.bean.jpa.PhotoEntity;
import org.backpacker4.mock.tool.MockValues;

public class PhotoEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public PhotoEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextLong() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public PhotoEntity createInstance( Long id ) {
		PhotoEntity entity = new PhotoEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setDescription( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setDatetaken( mockValues.nextDate() ) ; // java.util.Date 
		entity.setComment( mockValues.nextString(2147483647) ) ; // java.lang.String 
		entity.setFullphoto( mockValues.nextString(1000) ) ; // java.lang.String 
		entity.setThumbnail( mockValues.nextString(1000) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfAlbum( TODO ) ; // List<Album> 
		// setPosition( TODO ) ; // Position 
		// setListOfFeedback( TODO ) ; // List<Feedback> 
		// setListOfAppuser( TODO ) ; // List<Appuser> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<PhotoEntity> createList(int count) {
		List<PhotoEntity> list = new LinkedList<PhotoEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
