
/*
 * Created on 28 okt 2015 ( Time 11:01:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.backpacker4.mock;

import java.util.LinkedList;
import java.util.List;

import org.backpacker4.bean.jpa.UserRolesEntity;
import org.backpacker4.mock.tool.MockValues;

public class UserRolesEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public UserRolesEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public UserRolesEntity createInstance( Integer iduserRoles ) {
		UserRolesEntity entity = new UserRolesEntity();
		// Init Primary Key fields
		entity.setIduserRoles( iduserRoles) ;
		// Init Data fields
		entity.setUserrole( mockValues.nextString(45) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setAppuser( TODO ) ; // Appuser 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<UserRolesEntity> createList(int count) {
		List<UserRolesEntity> list = new LinkedList<UserRolesEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
